package repository

import (
	"context"
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"ultra-api-testing/internal/models"
)

// Sentinel errors for order repository operations
var (
	ErrOrderNotFound            = errors.New("order not found")
	ErrInvalidStatusTransition  = errors.New("invalid status transition")
	ErrInvalidOrderInput        = errors.New("invalid order input")
	ErrProductNotFound          = errors.New("product not found")
	ErrStoreRequiredForPickup   = errors.New("store_id is required for pickup delivery type")
	ErrAddressRequiredForDelivery = errors.New("delivery_address is required for delivery type")
)

// Validation regex patterns
var (
	emailRegex = regexp.MustCompile(`^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$`)
	phoneRegex = regexp.MustCompile(`^\+?[0-9\s\-\(\)]{7,20}$`)
)

// OrderRepository handles order database operations
type OrderRepository struct {
	pool *pgxpool.Pool
}

// NewOrderRepository creates a new order repository
func NewOrderRepository(pool *pgxpool.Pool) *OrderRepository {
	return &OrderRepository{pool: pool}
}

// CreateOrder creates a new order with items in a transaction
func (r *OrderRepository) CreateOrder(ctx context.Context, input *models.CreateOrderInput) (*models.OrderWithItems, error) {
	// Validate input
	if err := r.validateCreateOrderInput(input); err != nil {
		return nil, err
	}

	// Start transaction
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Create order (order_number generated by database function)
	orderQuery := `
		INSERT INTO orders (
			full_name, phone_number, email, delivery_type, delivery_address, store_id,
			payment_method, currency, status, notes, user_id, user_name, user_pfp
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
		RETURNING id, order_number, full_name, phone_number, email, delivery_type, delivery_address,
		          store_id, payment_method, total_amount, currency, status, notes,
		          user_id, user_name, user_pfp, created_at, updated_at
	`

	order := &models.Order{}
	err = tx.QueryRow(ctx, orderQuery,
		strings.TrimSpace(input.FullName),
		strings.TrimSpace(input.PhoneNumber),
		input.Email,
		input.DeliveryType,
		input.DeliveryAddress,
		input.StoreID,
		input.PaymentMethod,
		"MDL", // Default currency
		models.OrderStatusPending,
		input.Notes,
		input.UserID,
		input.UserName,
		input.UserPfp,
	).Scan(
		&order.ID,
		&order.OrderNumber,
		&order.FullName,
		&order.PhoneNumber,
		&order.Email,
		&order.DeliveryType,
		&order.DeliveryAddress,
		&order.StoreID,
		&order.PaymentMethod,
		&order.TotalAmount,
		&order.Currency,
		&order.Status,
		&order.Notes,
		&order.UserID,
		&order.UserName,
		&order.UserPfp,
		&order.CreatedAt,
		&order.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("create order: %w", err)
	}

	// Create order items with product snapshots
	var items []*models.OrderItem
	for _, itemInput := range input.Items {
		// Fetch product snapshot
		productQuery := `
			SELECT name, article, main_image_url, price_mdl
			FROM products
			WHERE id = $1
		`

		var productName string
		var productSKU *string
		var productImage *string
		var unitPrice float64

		err = tx.QueryRow(ctx, productQuery, itemInput.ProductID).Scan(
			&productName,
			&productSKU,
			&productImage,
			&unitPrice,
		)
		if err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return nil, fmt.Errorf("%w: %s", ErrProductNotFound, itemInput.ProductID)
			}
			return nil, fmt.Errorf("fetch product snapshot: %w", err)
		}

		// Calculate total price
		totalPrice := float64(itemInput.Quantity) * unitPrice

		// Insert order item
		itemQuery := `
			INSERT INTO order_items (
				order_id, product_id, product_name, product_sku, product_image,
				quantity, unit_price, total_price
			)
			VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
			RETURNING id, order_id, product_id, product_name, product_sku, product_image,
			          quantity, unit_price, total_price, created_at
		`

		item := &models.OrderItem{}
		err = tx.QueryRow(ctx, itemQuery,
			order.ID,
			itemInput.ProductID,
			productName,
			productSKU,
			productImage,
			itemInput.Quantity,
			unitPrice,
			totalPrice,
		).Scan(
			&item.ID,
			&item.OrderID,
			&item.ProductID,
			&item.ProductName,
			&item.ProductSKU,
			&item.ProductImage,
			&item.Quantity,
			&item.UnitPrice,
			&item.TotalPrice,
			&item.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("create order item: %w", err)
		}

		items = append(items, item)
	}

	// Fetch updated order with total_amount (calculated by trigger)
	err = tx.QueryRow(ctx, `
		SELECT total_amount FROM orders WHERE id = $1
	`, order.ID).Scan(&order.TotalAmount)
	if err != nil {
		return nil, fmt.Errorf("fetch order total: %w", err)
	}

	// Commit transaction
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("commit transaction: %w", err)
	}

	// Return order with items
	return &models.OrderWithItems{
		Order: order,
		Items: items,
	}, nil
}

// GetOrder returns an order with items by ID
func (r *OrderRepository) GetOrder(ctx context.Context, id uuid.UUID) (*models.OrderWithItems, error) {
	// Fetch order
	orderQuery := `
		SELECT
			o.id, o.order_number, o.full_name, o.phone_number, o.email,
			o.delivery_type, o.delivery_address, o.store_id, o.payment_method,
			o.total_amount, o.currency, o.status, o.notes,
			o.user_id, o.user_name, o.user_pfp, o.created_at, o.updated_at,
			s.name as store_name
		FROM orders o
		LEFT JOIN stores s ON s.id = o.store_id
		WHERE o.id = $1
	`

	order := &models.Order{}
	err := r.pool.QueryRow(ctx, orderQuery, id).Scan(
		&order.ID,
		&order.OrderNumber,
		&order.FullName,
		&order.PhoneNumber,
		&order.Email,
		&order.DeliveryType,
		&order.DeliveryAddress,
		&order.StoreID,
		&order.PaymentMethod,
		&order.TotalAmount,
		&order.Currency,
		&order.Status,
		&order.Notes,
		&order.UserID,
		&order.UserName,
		&order.UserPfp,
		&order.CreatedAt,
		&order.UpdatedAt,
		&order.StoreName,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrOrderNotFound
		}
		return nil, fmt.Errorf("get order: %w", err)
	}

	// Fetch order items
	itemsQuery := `
		SELECT
			id, order_id, product_id, product_name, product_sku, product_image,
			quantity, unit_price, total_price, created_at
		FROM order_items
		WHERE order_id = $1
		ORDER BY created_at
	`

	rows, err := r.pool.Query(ctx, itemsQuery, id)
	if err != nil {
		return nil, fmt.Errorf("query order items: %w", err)
	}
	defer rows.Close()

	var items []*models.OrderItem
	for rows.Next() {
		item := &models.OrderItem{}
		if err := rows.Scan(
			&item.ID,
			&item.OrderID,
			&item.ProductID,
			&item.ProductName,
			&item.ProductSKU,
			&item.ProductImage,
			&item.Quantity,
			&item.UnitPrice,
			&item.TotalPrice,
			&item.CreatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan order item: %w", err)
		}
		items = append(items, item)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate order items: %w", err)
	}

	return &models.OrderWithItems{
		Order: order,
		Items: items,
	}, nil
}

// GetOrderByNumber returns an order with items by order number
func (r *OrderRepository) GetOrderByNumber(ctx context.Context, orderNumber string) (*models.OrderWithItems, error) {
	// Fetch order
	orderQuery := `
		SELECT
			o.id, o.order_number, o.full_name, o.phone_number, o.email,
			o.delivery_type, o.delivery_address, o.store_id, o.payment_method,
			o.total_amount, o.currency, o.status, o.notes,
			o.user_id, o.user_name, o.user_pfp, o.created_at, o.updated_at,
			s.name as store_name
		FROM orders o
		LEFT JOIN stores s ON s.id = o.store_id
		WHERE o.order_number = $1
	`

	order := &models.Order{}
	err := r.pool.QueryRow(ctx, orderQuery, orderNumber).Scan(
		&order.ID,
		&order.OrderNumber,
		&order.FullName,
		&order.PhoneNumber,
		&order.Email,
		&order.DeliveryType,
		&order.DeliveryAddress,
		&order.StoreID,
		&order.PaymentMethod,
		&order.TotalAmount,
		&order.Currency,
		&order.Status,
		&order.Notes,
		&order.UserID,
		&order.UserName,
		&order.UserPfp,
		&order.CreatedAt,
		&order.UpdatedAt,
		&order.StoreName,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrOrderNotFound
		}
		return nil, fmt.Errorf("get order by number: %w", err)
	}

	// Fetch order items
	itemsQuery := `
		SELECT
			id, order_id, product_id, product_name, product_sku, product_image,
			quantity, unit_price, total_price, created_at
		FROM order_items
		WHERE order_id = $1
		ORDER BY created_at
	`

	rows, err := r.pool.Query(ctx, itemsQuery, order.ID)
	if err != nil {
		return nil, fmt.Errorf("query order items: %w", err)
	}
	defer rows.Close()

	var items []*models.OrderItem
	for rows.Next() {
		item := &models.OrderItem{}
		if err := rows.Scan(
			&item.ID,
			&item.OrderID,
			&item.ProductID,
			&item.ProductName,
			&item.ProductSKU,
			&item.ProductImage,
			&item.Quantity,
			&item.UnitPrice,
			&item.TotalPrice,
			&item.CreatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan order item: %w", err)
		}
		items = append(items, item)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate order items: %w", err)
	}

	return &models.OrderWithItems{
		Order: order,
		Items: items,
	}, nil
}

// UpdateOrder updates order details (not status or items)
func (r *OrderRepository) UpdateOrder(ctx context.Context, id uuid.UUID, input *models.UpdateOrderInput) (*models.Order, error) {
	// Build dynamic update query
	var setClauses []string
	var args []interface{}
	argNum := 1

	if input.FullName != nil {
		setClauses = append(setClauses, fmt.Sprintf("full_name = $%d", argNum))
		args = append(args, strings.TrimSpace(*input.FullName))
		argNum++
	}
	if input.PhoneNumber != nil {
		setClauses = append(setClauses, fmt.Sprintf("phone_number = $%d", argNum))
		args = append(args, strings.TrimSpace(*input.PhoneNumber))
		argNum++
	}
	if input.Email != nil {
		setClauses = append(setClauses, fmt.Sprintf("email = $%d", argNum))
		args = append(args, input.Email)
		argNum++
	}
	if input.DeliveryType != nil {
		setClauses = append(setClauses, fmt.Sprintf("delivery_type = $%d", argNum))
		args = append(args, *input.DeliveryType)
		argNum++
	}
	if input.DeliveryAddress != nil {
		setClauses = append(setClauses, fmt.Sprintf("delivery_address = $%d", argNum))
		args = append(args, input.DeliveryAddress)
		argNum++
	}
	if input.StoreID != nil {
		setClauses = append(setClauses, fmt.Sprintf("store_id = $%d", argNum))
		args = append(args, input.StoreID)
		argNum++
	}
	if input.PaymentMethod != nil {
		setClauses = append(setClauses, fmt.Sprintf("payment_method = $%d", argNum))
		args = append(args, *input.PaymentMethod)
		argNum++
	}
	if input.Notes != nil {
		setClauses = append(setClauses, fmt.Sprintf("notes = $%d", argNum))
		args = append(args, input.Notes)
		argNum++
	}

	if len(setClauses) == 0 {
		return r.getOrderByID(ctx, id)
	}

	setClauses = append(setClauses, "updated_at = NOW()")

	query := fmt.Sprintf(`
		UPDATE orders
		SET %s
		WHERE id = $%d
		RETURNING id, order_number, full_name, phone_number, email, delivery_type, delivery_address,
		          store_id, payment_method, total_amount, currency, status, notes,
		          user_id, user_name, user_pfp, created_at, updated_at
	`, strings.Join(setClauses, ", "), argNum)
	args = append(args, id)

	order := &models.Order{}
	err := r.pool.QueryRow(ctx, query, args...).Scan(
		&order.ID,
		&order.OrderNumber,
		&order.FullName,
		&order.PhoneNumber,
		&order.Email,
		&order.DeliveryType,
		&order.DeliveryAddress,
		&order.StoreID,
		&order.PaymentMethod,
		&order.TotalAmount,
		&order.Currency,
		&order.Status,
		&order.Notes,
		&order.UserID,
		&order.UserName,
		&order.UserPfp,
		&order.CreatedAt,
		&order.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrOrderNotFound
		}
		return nil, fmt.Errorf("update order: %w", err)
	}

	return order, nil
}

// UpdateOrderStatus updates the order status with validation
// Uses row-level locking to prevent race conditions when multiple requests
// attempt to update the same order's status concurrently
func (r *OrderRepository) UpdateOrderStatus(ctx context.Context, id uuid.UUID, newStatus string) (*models.Order, error) {
	// Validate new status
	if !models.IsValidOrderStatus(newStatus) {
		return nil, fmt.Errorf("invalid status: %s", newStatus)
	}

	// Start transaction
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Lock the row and get current status
	var currentStatus string
	err = tx.QueryRow(ctx, `SELECT status FROM orders WHERE id = $1 FOR UPDATE`, id).Scan(&currentStatus)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrOrderNotFound
		}
		return nil, fmt.Errorf("get current status: %w", err)
	}

	// Validate status transition
	if !models.CanTransitionTo(currentStatus, newStatus) {
		return nil, fmt.Errorf("%w: cannot transition from %s to %s", ErrInvalidStatusTransition, currentStatus, newStatus)
	}

	// Update status within transaction
	query := `
		UPDATE orders
		SET status = $1, updated_at = NOW()
		WHERE id = $2
		RETURNING id, order_number, full_name, phone_number, email, delivery_type, delivery_address,
		          store_id, payment_method, total_amount, currency, status, notes,
		          user_id, user_name, user_pfp, created_at, updated_at
	`

	order := &models.Order{}
	err = tx.QueryRow(ctx, query, newStatus, id).Scan(
		&order.ID,
		&order.OrderNumber,
		&order.FullName,
		&order.PhoneNumber,
		&order.Email,
		&order.DeliveryType,
		&order.DeliveryAddress,
		&order.StoreID,
		&order.PaymentMethod,
		&order.TotalAmount,
		&order.Currency,
		&order.Status,
		&order.Notes,
		&order.UserID,
		&order.UserName,
		&order.UserPfp,
		&order.CreatedAt,
		&order.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("update order status: %w", err)
	}

	// Commit transaction
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("commit transaction: %w", err)
	}

	return order, nil
}

// DeleteOrder deletes an order and its items (CASCADE)
func (r *OrderRepository) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	query := `DELETE FROM orders WHERE id = $1`

	cmdTag, err := r.pool.Exec(ctx, query, id)
	if err != nil {
		return fmt.Errorf("delete order: %w", err)
	}

	if cmdTag.RowsAffected() == 0 {
		return ErrOrderNotFound
	}

	return nil
}

// ListOrders returns orders with filters and pagination
func (r *OrderRepository) ListOrders(ctx context.Context, filters *models.OrderFilters, limit, offset int) ([]*models.Order, error) {
	query := `
		SELECT
			o.id, o.order_number, o.full_name, o.phone_number, o.email,
			o.delivery_type, o.delivery_address, o.store_id, o.payment_method,
			o.total_amount, o.currency, o.status, o.notes,
			o.user_id, o.user_name, o.user_pfp, o.created_at, o.updated_at,
			s.name as store_name
		FROM orders o
		LEFT JOIN stores s ON s.id = o.store_id
	`

	var conditions []string
	var args []interface{}
	argNum := 1

	if filters != nil {
		if filters.Search != "" {
			conditions = append(conditions, fmt.Sprintf("(o.order_number ILIKE $%d OR o.full_name ILIKE $%d OR o.phone_number ILIKE $%d)", argNum, argNum, argNum))
			args = append(args, "%"+filters.Search+"%")
			argNum++
		}
		if filters.Status != nil {
			conditions = append(conditions, fmt.Sprintf("o.status = $%d", argNum))
			args = append(args, *filters.Status)
			argNum++
		}
		if filters.PaymentMethod != nil {
			conditions = append(conditions, fmt.Sprintf("o.payment_method = $%d", argNum))
			args = append(args, *filters.PaymentMethod)
			argNum++
		}
		if filters.DeliveryType != nil {
			conditions = append(conditions, fmt.Sprintf("o.delivery_type = $%d", argNum))
			args = append(args, *filters.DeliveryType)
			argNum++
		}
		if filters.StoreID != nil {
			conditions = append(conditions, fmt.Sprintf("o.store_id = $%d", argNum))
			args = append(args, *filters.StoreID)
			argNum++
		}
		if filters.DateFrom != nil {
			conditions = append(conditions, fmt.Sprintf("o.created_at >= $%d", argNum))
			args = append(args, *filters.DateFrom)
			argNum++
		}
		if filters.DateTo != nil {
			conditions = append(conditions, fmt.Sprintf("o.created_at <= $%d", argNum))
			args = append(args, *filters.DateTo)
			argNum++
		}
		if filters.UserID != nil {
			conditions = append(conditions, fmt.Sprintf("o.user_id = $%d", argNum))
			args = append(args, *filters.UserID)
			argNum++
		}
	}

	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}

	query += " ORDER BY o.created_at DESC"

	// Add pagination
	query += fmt.Sprintf(" LIMIT $%d OFFSET $%d", argNum, argNum+1)
	args = append(args, limit, offset)

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("query orders: %w", err)
	}
	defer rows.Close()

	var orders []*models.Order
	for rows.Next() {
		order := &models.Order{}
		if err := rows.Scan(
			&order.ID,
			&order.OrderNumber,
			&order.FullName,
			&order.PhoneNumber,
			&order.Email,
			&order.DeliveryType,
			&order.DeliveryAddress,
			&order.StoreID,
			&order.PaymentMethod,
			&order.TotalAmount,
			&order.Currency,
			&order.Status,
			&order.Notes,
			&order.UserID,
			&order.UserName,
			&order.UserPfp,
			&order.CreatedAt,
			&order.UpdatedAt,
			&order.StoreName,
		); err != nil {
			return nil, fmt.Errorf("scan order: %w", err)
		}
		orders = append(orders, order)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate orders: %w", err)
	}

	return orders, nil
}

// CountOrders returns the total count of orders with filters
func (r *OrderRepository) CountOrders(ctx context.Context, filters *models.OrderFilters) (int, error) {
	query := `SELECT COUNT(*) FROM orders o`

	var conditions []string
	var args []interface{}
	argNum := 1

	if filters != nil {
		if filters.Search != "" {
			conditions = append(conditions, fmt.Sprintf("(o.order_number ILIKE $%d OR o.full_name ILIKE $%d OR o.phone_number ILIKE $%d)", argNum, argNum, argNum))
			args = append(args, "%"+filters.Search+"%")
			argNum++
		}
		if filters.Status != nil {
			conditions = append(conditions, fmt.Sprintf("o.status = $%d", argNum))
			args = append(args, *filters.Status)
			argNum++
		}
		if filters.PaymentMethod != nil {
			conditions = append(conditions, fmt.Sprintf("o.payment_method = $%d", argNum))
			args = append(args, *filters.PaymentMethod)
			argNum++
		}
		if filters.DeliveryType != nil {
			conditions = append(conditions, fmt.Sprintf("o.delivery_type = $%d", argNum))
			args = append(args, *filters.DeliveryType)
			argNum++
		}
		if filters.StoreID != nil {
			conditions = append(conditions, fmt.Sprintf("o.store_id = $%d", argNum))
			args = append(args, *filters.StoreID)
			argNum++
		}
		if filters.DateFrom != nil {
			conditions = append(conditions, fmt.Sprintf("o.created_at >= $%d", argNum))
			args = append(args, *filters.DateFrom)
			argNum++
		}
		if filters.DateTo != nil {
			conditions = append(conditions, fmt.Sprintf("o.created_at <= $%d", argNum))
			args = append(args, *filters.DateTo)
			argNum++
		}
		if filters.UserID != nil {
			conditions = append(conditions, fmt.Sprintf("o.user_id = $%d", argNum))
			args = append(args, *filters.UserID)
			argNum++
		}
	}

	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}

	var count int
	err := r.pool.QueryRow(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("count orders: %w", err)
	}

	return count, nil
}

// GetOrderStats returns order statistics
func (r *OrderRepository) GetOrderStats(ctx context.Context) (*models.OrderStats, error) {
	query := `
		SELECT
			COUNT(*) as total_orders,
			COUNT(*) FILTER (WHERE status = 'pending') as pending_orders,
			COUNT(*) FILTER (WHERE status = 'confirmed') as confirmed_orders,
			COUNT(*) FILTER (WHERE status = 'processing') as processing_orders,
			COUNT(*) FILTER (WHERE status = 'shipped') as shipped_orders,
			COUNT(*) FILTER (WHERE status = 'delivered') as delivered_orders,
			COUNT(*) FILTER (WHERE status = 'cancelled') as cancelled_orders,
			COALESCE(SUM(total_amount), 0) as total_revenue,
			COALESCE(AVG(total_amount), 0) as average_order_value,
			COUNT(*) FILTER (WHERE DATE(created_at) = CURRENT_DATE) as today_orders,
			COALESCE(SUM(total_amount) FILTER (WHERE DATE(created_at) = CURRENT_DATE), 0) as today_revenue
		FROM orders
	`

	stats := &models.OrderStats{}
	err := r.pool.QueryRow(ctx, query).Scan(
		&stats.TotalOrders,
		&stats.PendingOrders,
		&stats.ConfirmedOrders,
		&stats.ProcessingOrders,
		&stats.ShippedOrders,
		&stats.DeliveredOrders,
		&stats.CancelledOrders,
		&stats.TotalRevenue,
		&stats.AverageOrderValue,
		&stats.TodayOrders,
		&stats.TodayRevenue,
	)
	if err != nil {
		return nil, fmt.Errorf("get order stats: %w", err)
	}

	return stats, nil
}

// ExportOrders returns all orders matching filters for CSV export
func (r *OrderRepository) ExportOrders(ctx context.Context, filters *models.OrderFilters) ([]*models.Order, error) {
	query := `
		SELECT
			o.id, o.order_number, o.full_name, o.phone_number, o.email,
			o.delivery_type, o.delivery_address, o.store_id, o.payment_method,
			o.total_amount, o.currency, o.status, o.notes,
			o.user_id, o.user_name, o.user_pfp, o.created_at, o.updated_at,
			s.name as store_name
		FROM orders o
		LEFT JOIN stores s ON s.id = o.store_id
	`

	var conditions []string
	var args []interface{}
	argNum := 1

	if filters != nil {
		if filters.Search != "" {
			conditions = append(conditions, fmt.Sprintf("(o.order_number ILIKE $%d OR o.full_name ILIKE $%d OR o.phone_number ILIKE $%d)", argNum, argNum, argNum))
			args = append(args, "%"+filters.Search+"%")
			argNum++
		}
		if filters.Status != nil {
			conditions = append(conditions, fmt.Sprintf("o.status = $%d", argNum))
			args = append(args, *filters.Status)
			argNum++
		}
		if filters.PaymentMethod != nil {
			conditions = append(conditions, fmt.Sprintf("o.payment_method = $%d", argNum))
			args = append(args, *filters.PaymentMethod)
			argNum++
		}
		if filters.DeliveryType != nil {
			conditions = append(conditions, fmt.Sprintf("o.delivery_type = $%d", argNum))
			args = append(args, *filters.DeliveryType)
			argNum++
		}
		if filters.StoreID != nil {
			conditions = append(conditions, fmt.Sprintf("o.store_id = $%d", argNum))
			args = append(args, *filters.StoreID)
			argNum++
		}
		if filters.DateFrom != nil {
			conditions = append(conditions, fmt.Sprintf("o.created_at >= $%d", argNum))
			args = append(args, *filters.DateFrom)
			argNum++
		}
		if filters.DateTo != nil {
			conditions = append(conditions, fmt.Sprintf("o.created_at <= $%d", argNum))
			args = append(args, *filters.DateTo)
			argNum++
		}
		if filters.UserID != nil {
			conditions = append(conditions, fmt.Sprintf("o.user_id = $%d", argNum))
			args = append(args, *filters.UserID)
			argNum++
		}
	}

	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}

	query += " ORDER BY o.created_at DESC"

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("query orders for export: %w", err)
	}
	defer rows.Close()

	var orders []*models.Order
	for rows.Next() {
		order := &models.Order{}
		if err := rows.Scan(
			&order.ID,
			&order.OrderNumber,
			&order.FullName,
			&order.PhoneNumber,
			&order.Email,
			&order.DeliveryType,
			&order.DeliveryAddress,
			&order.StoreID,
			&order.PaymentMethod,
			&order.TotalAmount,
			&order.Currency,
			&order.Status,
			&order.Notes,
			&order.UserID,
			&order.UserName,
			&order.UserPfp,
			&order.CreatedAt,
			&order.UpdatedAt,
			&order.StoreName,
		); err != nil {
			return nil, fmt.Errorf("scan order: %w", err)
		}
		orders = append(orders, order)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate orders: %w", err)
	}

	return orders, nil
}

// getOrderByID is a helper to fetch just the order without items
func (r *OrderRepository) getOrderByID(ctx context.Context, id uuid.UUID) (*models.Order, error) {
	query := `
		SELECT
			id, order_number, full_name, phone_number, email, delivery_type, delivery_address,
			store_id, payment_method, total_amount, currency, status, notes,
			user_id, user_name, user_pfp, created_at, updated_at
		FROM orders
		WHERE id = $1
	`

	order := &models.Order{}
	err := r.pool.QueryRow(ctx, query, id).Scan(
		&order.ID,
		&order.OrderNumber,
		&order.FullName,
		&order.PhoneNumber,
		&order.Email,
		&order.DeliveryType,
		&order.DeliveryAddress,
		&order.StoreID,
		&order.PaymentMethod,
		&order.TotalAmount,
		&order.Currency,
		&order.Status,
		&order.Notes,
		&order.UserID,
		&order.UserName,
		&order.UserPfp,
		&order.CreatedAt,
		&order.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrOrderNotFound
		}
		return nil, fmt.Errorf("get order: %w", err)
	}

	return order, nil
}

// validateCreateOrderInput validates order creation input
func (r *OrderRepository) validateCreateOrderInput(input *models.CreateOrderInput) error {
	// Validate required fields
	if strings.TrimSpace(input.FullName) == "" {
		return fmt.Errorf("%w: full_name is required", ErrInvalidOrderInput)
	}
	if strings.TrimSpace(input.PhoneNumber) == "" {
		return fmt.Errorf("%w: phone_number is required", ErrInvalidOrderInput)
	}

	// Validate email format if provided
	if input.Email != nil && *input.Email != "" {
		if !emailRegex.MatchString(*input.Email) {
			return fmt.Errorf("%w: invalid email format", ErrInvalidOrderInput)
		}
	}

	// Validate phone number format
	phone := strings.ReplaceAll(input.PhoneNumber, " ", "")
	if !phoneRegex.MatchString(phone) {
		return fmt.Errorf("%w: invalid phone number format", ErrInvalidOrderInput)
	}

	// Validate delivery type
	if !models.IsValidDeliveryType(input.DeliveryType) {
		return fmt.Errorf("%w: invalid delivery_type", ErrInvalidOrderInput)
	}

	// Validate delivery-specific fields
	if input.DeliveryType == models.DeliveryTypePickup && input.StoreID == nil {
		return ErrStoreRequiredForPickup
	}
	if input.DeliveryType == models.DeliveryTypeDelivery && input.DeliveryAddress == nil {
		return ErrAddressRequiredForDelivery
	}

	// Validate payment method
	if !models.IsValidPaymentMethod(input.PaymentMethod) {
		return fmt.Errorf("%w: invalid payment_method", ErrInvalidOrderInput)
	}

	// Validate items
	if len(input.Items) == 0 {
		return fmt.Errorf("%w: at least one item is required", ErrInvalidOrderInput)
	}

	// Validate maximum items per order
	if len(input.Items) > 100 {
		return fmt.Errorf("%w: maximum 100 items per order", ErrInvalidOrderInput)
	}

	for i, item := range input.Items {
		if item.Quantity <= 0 {
			return fmt.Errorf("%w: item %d quantity must be greater than 0", ErrInvalidOrderInput, i)
		}
	}

	return nil
}

// CreateComment adds a comment to an order
func (r *OrderRepository) CreateComment(ctx context.Context, orderID uuid.UUID, adminID, adminName, content string) (*models.OrderComment, error) {
	query := `
		INSERT INTO order_comments (order_id, admin_id, admin_name, content)
		VALUES ($1, $2, $3, $4)
		RETURNING id, order_id, admin_id, admin_name, content, created_at
	`

	var comment models.OrderComment
	err := r.pool.QueryRow(ctx, query, orderID, adminID, adminName, content).Scan(
		&comment.ID,
		&comment.OrderID,
		&comment.AdminID,
		&comment.AdminName,
		&comment.Content,
		&comment.CreatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create comment: %w", err)
	}

	return &comment, nil
}

// GetCommentsByOrderID retrieves all comments for an order
func (r *OrderRepository) GetCommentsByOrderID(ctx context.Context, orderID uuid.UUID) ([]*models.OrderComment, error) {
	query := `
		SELECT id, order_id, admin_id, admin_name, content, created_at
		FROM order_comments
		WHERE order_id = $1
		ORDER BY created_at DESC
	`

	rows, err := r.pool.Query(ctx, query, orderID)
	if err != nil {
		return nil, fmt.Errorf("failed to query comments: %w", err)
	}
	defer rows.Close()

	var comments []*models.OrderComment
	for rows.Next() {
		var c models.OrderComment
		if err := rows.Scan(
			&c.ID, &c.OrderID, &c.AdminID, &c.AdminName, &c.Content, &c.CreatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan comment: %w", err)
		}
		comments = append(comments, &c)
	}

	return comments, nil
}
